import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import UserSync from "./UserSync";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import {Toaster} from 'sonner'
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <UserSync />

      <Navbar></Navbar>
      <html lang="en">
        <body
          className={`${geistSans.variable} bg-neutral-900 ${geistMono.variable} antialiased`}
        >
          {children}
          <Toaster position="top-center" richColors />
        </body>
        <Footer></Footer>
      </html>
    </ClerkProvider>
  );
}
